name: Size Limit
on: [pull_request]
env:
  CARGO_TERM_COLOR: always
  CI_JOB_NUMBER: 1
jobs:
  size-limit:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clean_script: cleanup
